### ISSUE TITLE
slicer bbox annotations

### ISSUE THREAD

**Issue by sypersf** [acl21/image_bbox_slicer#3]
I have used the tool to slice my image and its bbox annotations(keep partial labels and ignore empty tiles). Some bboxes coordinates are -1, and I wonder what made this outcomes.

**Comment by acl21** [comment]
My apologies for this late reply. 

I definitely need more info about the issue. Did you spot the problem? Was it a bug?

**Comment by sypersf** [comment]
The problem is resolved and it's caused by my mistake in preparing
annotations. Thanks for your reply.

Akshay L Chandra <notifications@github.com> 于 2021年2月16日周二 00:42写道：

**Comment by acl21** [comment]
Okay great. :)
