### ISSUE TITLE
Same name + index

### ISSUE THREAD

**Issue by ccimarp1990** [acl21/image_bbox_slicer#5]
I would to have the original name of the image/annotation following a index to distinguish different files. How can I change the code?

**Comment by acl21** [comment]
Can you elaborate more with an example?

**Comment by ccimarp1990** [comment]
For example,
my original image called "image1", "image2","image3",.... I would like to add to each tile image the original name plus a sequencial number.
image1_1; image1_2;.....

**Comment by acl21** [comment]
For images, you'd have to change the **for** loop at line 234 in image_bbox_slicer/main.py to something like this:
```
for tile_id, tile in enumerate(tiles):
    new_im = im.crop(tile)
    img_id_str = str('{}_{}'.format(file_name, tile_id+1))
    if len(self._ignore_tiles) != 0:
        if img_id_str in self._ignore_tiles:
            self._ignore_tiles.remove(img_id_str)
            continue
    new_im.save(
        '{}/{}.{}'.format(self.IMG_DST, img_id_str, file_type))
    new_ids.append(img_id_str)
    img_no += 1
```

I did not test this code, I just wrote it out by copy-pasting from the source just so you get the idea. Make sure to do similar changes wherever I am initializing the image id string e.g., line 316 where sliced annotations can be renamed.
