### ISSUE TITLE
Merge sliced annotations

### ISSUE THREAD

**Issue by felixmagnell** [acl21/image_bbox_slicer#7]
Hi!
First of all i just want to say what a great tool this is!

I'm wondering if there is any possibility to merge sliced annotations back to it's original image?

Let's say i slice an image, train a model for object detection, predict on a new image sliced as the training data. I would then want to merge the predicted bounding boxes with the non-sliced image.

Any idea how i would go about?

Cheers!

**Comment by acl21** [comment]
Hi, 

I am glad you found this tool useful. Thank you! 

Merging should be easy. Set `save_before_after_map = True`  before you slice your data, this way you get a table as follows in a csv file:
```
| old_name   | new_names                       |
|------------|---------------------------------|
| 2102       | 000001, 000002, 000003, 000004  |
| 3931       | 000005, 000005, 000007, 000008  |
| test_image | 000009, 000010, 000011, 000012  |
| ...        | ...                             |
```
This will allow you to map each slice back to its parent. Now you can just run a for-loop to read each 4 files at a time and merge them appropriately. You can see [this answer from StackOverflow](https://stackoverflow.com/a/30228789) for details on how to merge images vertically and horizontally. 

I hope this helps. Good luck!
